### ISSUE TITLE
REPL environment unable to accept empty string

### ISSUE THREAD

**Issue by ampan98** [team-stack-underflow/runnable-backend#4] opened 2020-07-26 12:55 UTC
A standard REPL environment is able to accept an empty user input.

**Comment by wltan** [comment] 2020-07-26 13:03
The root cause is that Amazon SQS is unable to accept empty message bodies.

Proposed solution is to "box" each message by appending some string to make it non-empty, then "unbox" messages when receiving.

**Comment by wltan** [comment] 2020-07-26 16:27
Fixes have been merged

**Closed as completed by wltan** 2020-07-26 16:27 UTC
